name: Trigger auto deployment for container-app-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ azure-app-insigths ]
    paths:
    - 'azure-app-insigths/spring-programatic/**'
    - '.github/workflows/container-app-2-AutoDeployTrigger-083b5792-d0f6-4d3f-80a9-32fd1552151f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: artus1containerregistry.azurecr.io
          username: ${{ secrets.CONTAINERAPP2_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: artus1containerregistry.azurecr.io/container-app-2:${{ github.sha }}
          file: ./azure-app-insigths/spring-programatic/Dockerfile
          context: ./azure-app-insigths/spring-programatic/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-2 -g resource-group-container-app-1 --server artus1containerregistry.azurecr.io --username  ${{ secrets.CONTAINERAPP2_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP2_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-2 -g resource-group-container-app-1 --image artus1containerregistry.azurecr.io/container-app-2:${{ github.sha }}
